e_dflmer<-function(explaining=0){

if(explaining==0) {
cat("  ", '\n')
cat("\033[1;32m## lmer dataset ----------- \033[0m", '\n')
cat("  # HLM 완벽 가이드 dataset ----", '\n')
cat("  1) salary_data ", '\n')
cat("  2) therapie ", '\n')
cat("   ", '\n')
cat("  # Carolyn dataset ----", '\n')
cat("  depression_data_long", '\n')
cat("  hsb1data", '\n')
cat("  hsb2data", '\n')
cat("  lsat6_long_data", '\n')
cat("  nels_data", '\n')
cat("  nels10", '\n')
cat("  respitory", '\n')
cat("  RIESBY_data_time_varying_for_r", '\n')
cat("   ", '\n')
cat("\033[1;32m## lmer dataset ----------- \033[0m", '\n')
cat("   ", '\n')
cat("  ﻿icc <- function(modl){  ", '\n')
cat("       vars <- as.data.frame(VarCorr(modl))[4]", '\n')
cat("       total <- sum(vars)  tau00 <- vars[1,1]", '\n')
cat("       icc <- tau00/total", '\n')
cat("       return(icc)  }  # example of how to use this ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("   ", '\n')
cat("  library(dplyr); library(dflmer); ﻿library(lme4); library(lmerTest); library(aj412s)", '\n')
cat("  ", '\n')
cat("\033[1;33m  ## Intercept Only Model(IOM) M1 ----- \033[0m", '\n')
cat("     intercept.only.model <- lmer(salary ~ 1  + (1  | firma), data = df, REML = TRUE)", '\n')
cat("     ranova(intercept.only.model)", '\n')
cat("  ", '\n')
cat("\033[1;33m  ## Radnom Intercept Model(RIM) M2 ----- \033[0m", '\n')
cat("     random.intercept.model <-  lmer(salary ~ experience + (1  | firma), data = df, REML = TRUE)", '\n')
cat("     df$random.intercept.preds <-  predict(random.intercept.model)", '\n')
cat("     ranef(random.intercept.model)  # obtain the individual random effects υ0i", '\n')
cat("  ", '\n')
cat("\033[1;33  ## Random Coefficients Modell (RCM) M3 ------\033[0m", '\n')
cat("     random.coefficients.model <-  lmer(salary ~ experience + (experience | firma), data = df, REML = TRUE)", '\n')
cat("     df$random.coefficients.preds <-  predict(random.coefficients.model)", '\n')
cat("     ranef(random.coefficients.model)", '\n')
cat("  ", '\n')
cat("  # Comparing Models", '\n')
cat("     ranova(random.coefficients.model)", '\n')
cat("     anova(random.coefficients.model, random.intercept.model, refit = FALSE)", '\n')
cat("     0.5*pchisq(10.011, 1, lower.tail = FALSE) + 0.5*pchisq(10.011, 2, lower.tail = FALSE)", '\n')
cat("  ", '\n')
cat("\033[1;33m  ## Context effect model (CM) : M4 -----\033[0m", '\n')
cat("     df <- df %>% group_by(firma) %>% ", '\n')
cat("     mutate(experience_gm = mean(experience), experience_gc = experience - experience_gm) %>%", '\n')
cat("     ungroup() %>% dplyr::select(firma, sector, experience, experience_gm, experience_gc, salary)", '\n')
cat("  ", '\n')
cat("     df %>% group_by(firma) %>% summarise(experience_gm = mean(experience_gm)) %>% ungroup()", '\n')
cat("  ", '\n')
cat("     context.model <- lmer(salary ~ experience_gc + experience_gm + (1|firma), data = df, REML = TRUE)", '\n')
cat("     df$context.model.preds <- predict(context.model)", '\n')
cat("  ", '\n')
cat("\033[1;33m  ## General intercept-as-outcome model (IAOM) M4 ----- \033[0m", '\n')
cat("     intercept.as.outcome.model <- lmer(salary ~ experience + sector + (experience | firma), data = df, REML = TRUE) ", '\n')
cat("  ", '\n')
cat("\033[1;33m  ## Slope-as-outcome model M5-----\033[0m", '\n')
cat("     slope.as.outcome.model <- lmer(salary ~ experience*sector + (experience | firma), data = df, REML = TRUE)", '\n')
cat("  ", '\n')
cat("  # Comparing Models", '\n')
cat("     ranova(slope.as.outcome.model)", '\n')
cat("     0.5*pchisq(5.0152, 1, lower.tail = FALSE) + 0.5*pchisq(5.0152, 2, lower.tail = FALSE)", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')

cat("  library(dplyr); library(dflmer); ﻿library(lme4); library(lmerTest); library(aj412s)", '\n')
cat("  ﻿hsb1 <- hsb1", '\n')
cat("  ﻿hsb2 <- hsb2", '\n')
cat("  ﻿hsb <- merge(hsb1,hsb2, by=c('id'))", '\n')
cat("  ", '\n')
cat("  ## Making mean variables -----", '\n')
cat("  ﻿meanminority  <- aggregate(minority ~ id , data=hsb, mean)", '\n')
cat("  names(meanminority) <- c('id', 'meanminority')", '\n')
cat("  hsb <- merge(hsb,meanminority, by =c('id'))", '\n')
cat("  ", '\n')
cat("  meanfemale  <- aggregate(female ~ id , data=hsb, mean)", '\n')
cat("  names(meanfemale) <- c('id', 'meanfemale')", '\n')
cat("  hsb <- merge(hsb,meanfemale, by =c('id'))", '\n')
cat("  ", '\n')
cat("  ## Random intercept -----", '\n')
cat("     ﻿model0 <- lmer(mathach ~ 1 + (1 | id), data=hsb, REML=FALSE)", '\n')
cat("     icc(model0)", '\n')
cat("  # Calc by Hand: ﻿icc <- 8.553/(8.553+39.148)", '\n')
cat("  ", '\n')
cat("  ## ﻿Random intercept and slope for centered ses -----", '\n')
cat("  # By centering here, we will be looking at the impact of where a student is relavtiave to their peers in terms of SES.", '\n')
cat("     model1 <- lmer(mathach ~ 1 + cses + (1 | id), data=hsb, REML=FALSE)", '\n')
cat("  ", '\n')
cat("  ## ﻿Random intercept and slope & meanses for ses -----", '\n')
cat("     model2 <- lmer(mathach ~ 1 + cses  + (1 + cses| id), data=hsb, REML=FALSE)", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')

cat("  ## ﻿Discrete Level 1 predictors (fixed effects) -----", '\n')
cat("  # Note female and minority are dummy (i.e., I have not declared them to be factors in this model)", '\n')
cat("     model.d1 <- lmer(mathach ~ 1 + cses  + female + minority+ (1 + cses| id), data=hsb, REML=FALSE)", '\n')
cat("     model.3 <- lmer(mathach ~ 1 + cses  + meanses + cses*meanses + (1 + cses| id), data=hsb, REML=FALSE", '\n')
cat("  ", '\n')
cat("  ", '\n')
cat("  # Logit Model -----------", '\n')
cat("  ﻿library(lme4); library(lmerTest); library(gee); library(dflmer)", '\n')
cat("     depress <- opencsv(depression_data_long.csv)", '\n')
cat("  ﻿   model1a <- glm(y ~ severe +  Rx + time + Rx*time, data=depress, family=binomial)", '\n')
cat("  ", '\n')
cat("  # ﻿GEE using exchangable ----------- ", '\n')
cat("     model.gee <- gee(y ~ severe  + Rx + time + Rx*time, id, data=depress, family=binomial, corstr='exchangeable') ", '\n')
cat("  ﻿   summary(model.gee)", '\n')
cat("  ", '\n')

} }

