e_dflmer<-function(explaining=0){

if(explaining==0) {
cat("  ", '\n')
cat("\033[1;32m## lmer dataset ----------- \033[0m", '\n')
cat("  # HLM 완벽 가이드 dataset ----", '\n')
cat("    1) salary_data ", '\n')
cat("    2) therapie ", '\n')
cat("   ", '\n')
cat("  # Carolyn dataset ----", '\n')
cat("    depression_data_long", '\n')
cat("    hsb1data", '\n')
cat("    hsb2data", '\n')
cat("    lsat6_long_data", '\n')
cat("    nels_data", '\n')
cat("    nels10", '\n')
cat("    respitory", '\n')
cat("    RIESBY_data_time_varying_for_r", '\n')
cat("  # Bodo Winter dataset ----", '\n')
cat("    politeness_data", '\n')
cat("   ", '\n')
cat("\033[1;32m## lmer dataset ----------- \033[0m", '\n')
cat("   ", '\n')
cat("  ﻿icc <- function(modl){  ", '\n')
cat("       vars <- as.data.frame(VarCorr(modl))[4]", '\n')
cat("       total <- sum(vars)", '\n')
cat("       tau00 <- vars[1,1]", '\n')
cat("       icc <- tau00/total", '\n')
cat("       return(icc)  }  # example of how to use this ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("   ", '\n')
cat("  library(nlme); library(optimx) ", '\n')
cat("  IOM <- lme(wellbeing~week5 + group, random=~week5|id, data=df, control = lmeControl(maxIter = 1000, msMaxIter = 1000) ) ", '\n')
cat("  IOM <- lme(salary~experience + sector, random=~1|firma, data=df,   ", '\n')
cat("             control=lmeControl(opt='optim', optCtrl=list(method='L-BFGS-B')) ", '\n')
cat("   ", '\n')
cat("  library(dplyr); library(dflmer); ﻿library(lme4); library(lmerTest); library(aj412s); library(optimx)", '\n')
cat("  ", '\n')
cat("\033[1;33m## Intercept Only Model(IOM) M1 ----- \033[0m", '\n')
cat("     IOM <- lmer(salary ~ 1  + (1 | firma), data = df, REML = TRUE, ﻿control = lmerControl(optimizer ='Nelder_Mead') ) ", '\n')
cat("     IOM <- lmer(salary ~ 1  + (1 | firma), data = df, REML = TRUE, ﻿control = lmerControl(optimizer ='optimx',  ", '\n')
cat("             optCtrl=list(method='L-BFGS-B')) ) ", '\n')
cat("     ranova(IOM)", '\n')
cat("  ", '\n')
cat("\033[1;33m## Radnom Intercept Model(RIM) M2 ----- \033[0m", '\n')
cat("     random.intercept.model <-  lmer(salary ~ experience + (1 | firma), data = df, REML = TRUE)", '\n')
cat("     df$random.intercept.preds <-  predict(random.intercept.model)", '\n')
cat("     ranef(random.intercept.model) ", '\n')
cat("  ", '\n')
cat("\033[1;33m## Random Coefficients Modell (RCM) M3 ------ \033[0m ", '\n')
cat("     random.coefficients.model <-  lmer(salary ~ experience + (1 + experience | firma), data = df, REML = TRUE)", '\n')
cat("     df$random.coefficients.preds <-  predict(random.coefficients.model)", '\n')
cat("     ranef(random.coefficients.model)", '\n')
cat("  ", '\n')
cat("\033[1;31m     ## Comparing Models ----- \033[0m", '\n')
cat("     ranova(random.coefficients.model)", '\n')
cat("     anova(random.coefficients.model, random.intercept.model, refit = FALSE)", '\n')
cat("     0.5*pchisq(10.011, 1, lower.tail = FALSE) + 0.5*pchisq(10.011, 2, lower.tail = FALSE)", '\n')
cat("  ", '\n')
cat("\033[1;33m## Context effect model (CM) : M4 -----\033[0m", '\n')
cat("\033[1;33m## gc:Level-1변수, gm:Level-2변수, gc는 기업 평균에서 벗어난 개인의 experience\033[0m", '\n')
cat("     df <- df %>% group_by(firma) %>% ", '\n')
cat("     mutate(experience_gm = mean(experience), experience_gc = experience - experience_gm) %>%", '\n')
cat("     ungroup() %>% dplyr::select(firma, sector, experience, experience_gm, experience_gc, salary)", '\n')
cat("  ", '\n')
cat("     df %>% group_by(firma) %>% summarise(experience_gm = mean(experience_gm)) %>% ungroup()", '\n')
cat("  ", '\n')
cat("\033[1;31m     ##Context effect Model \033[0m", '\n')
cat("     context.model <- lmer(salary ~ experience_gc + experience_gm + (1 | firma), data = df, REML = TRUE)", '\n')
cat("  ", '\n')
cat("\033[1;33m## General intercept-as-outcome model (IAOM) M4 ----- \033[0m", '\n')
cat("\033[1;31m## random intercept가 있고, random slope는 있거나 또는 없어도 됨\033[0m", '\n')
cat("\033[1;31m## 독립변수로 Level-1에서 experience가 있고 \033[0m", '\n')
cat("\033[1;31m## Level-2에 experience는 있어도 그만, 없어도 그만임 \033[0m", '\n')
cat("\033[1;31m## Level-1에 experience가 있고, Level2에서 experience의 slope가 어떻게 변하는지 알고자 할 때 사용 \033[0m", '\n')
cat("     intercept.as.outcome.model <- lmer(salary ~ experience + sector + (1 + experience | firma), data = df, REML = TRUE) ", '\n')
cat("  ", '\n')
cat("\033[1;33m## Slope-As-Outcome Model M5-----\033[0m", '\n')
cat("     slope.as.outcome.model <- lmer(salary ~ experience + sector + (experience:sector) + ( 1 + experience | firma), data = df, REML = TRUE)", '\n')
cat("\033[1;31m## experience의 기울기 분산이 Level-2 변수인 sector에 영향을 받는가?\033[0m", '\n')
cat("\033[1;31m## 상호작용항을 포함 시킨 후, ranova검정을 하면 variance 감소를 확인함\033[0m", '\n')
cat("     ranova(slope.as.outcome.model)", '\n')
cat("     # ranova(slope.as.outcome.model)의 비교모델", '\n')
cat("     # salary~experience + sector + (experience:sector) + (1|firma)", '\n')
cat("  ", '\n')
cat("\033[1;32     ## Comparing Models ----- \033[0m", '\n')
cat("     ranova(slope.as.outcome.model)", '\n')
cat("     0.5*pchisq(5.0152, 1, lower.tail = FALSE) + 0.5*pchisq(5.0152, 2, lower.tail = FALSE)", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("  library(dplyr); library(dflmer); ﻿library(lme4); library(lmerTest); library(aj412s)", '\n')
cat("  ﻿hsb1 <- hsb1", '\n')
cat("  ﻿hsb2 <- hsb2", '\n')
cat("  ﻿hsb <- merge(hsb1,hsb2, by=c('id'))", '\n')
cat("  ", '\n')

cat("\033[1;33m## Making mean variables -----\033[0m ", '\n')

cat("  ﻿meanminority  <- aggregate(minority ~ id , data=hsb, mean)", '\n')
cat("  names(meanminority) <- c('id', 'meanminority')", '\n')
cat("  hsb <- merge(hsb,meanminority, by =c('id'))", '\n')
cat("  ", '\n')
cat("  meanfemale  <- aggregate(female ~ id , data=hsb, mean)", '\n')
cat("  names(meanfemale) <- c('id', 'meanfemale')", '\n')
cat("  hsb <- merge(hsb,meanfemale, by =c('id'))", '\n')
cat("  ", '\n')
cat("\033[1;33m## Random intercept -----\033[0m ", '\n')
cat("     ﻿model0 <- lmer(mathach ~ 1 + (1 | id), data=hsb, REML=FALSE)", '\n')
cat("     icc(model0)", '\n')
cat("  # Calc by Hand: ﻿icc <- 8.553/(8.553+39.148)", '\n')
cat("  ", '\n')
cat("\033[1;33m## ﻿Random intercept and slope for centered ses -----\033[0m ", '\n')
cat("  # By centering here, we will be looking at the impact of where a student is relavtiave to their peers in terms of SES.", '\n')
cat("     model1 <- lmer(mathach ~ 1 + cses + (1 | id), data=hsb, REML=FALSE)", '\n')
cat("  ", '\n')
cat("\033[1;33m## ﻿Random intercept and slope & meanses for ses -----\033[0m ", '\n')
cat("     model2 <- lmer(mathach ~ 1 + cses  + (1 + cses| id), data=hsb, REML=FALSE)", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')

cat("\033[1;33m## ﻿Discrete Level 1 predictors (fixed effects) -----\033[0m ", '\n')
cat("  # Note female and minority are dummy (i.e., I have not declared them to be factors in this model)", '\n')
cat("     model.d1 <- lmer(mathach ~ 1 + cses  + female + minority+ (1 + cses| id), data=hsb, REML=FALSE)", '\n')
cat("     model.3 <- lmer(mathach ~ 1 + cses  + meanses + cses*meanses + (1 + cses| id), data=hsb, REML=FALSE", '\n')
cat("  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## Logit Model -----------\033[0m ", '\n')
cat("  ﻿library(lme4); library(lmerTest); library(gee); library(dflmer)", '\n')
cat("     depress <- opencsv(depression_data_long.csv)", '\n')
cat("  ﻿   model1a <- glm(y ~ severe +  Rx + time + Rx*time, data=depress, family=binomial)", '\n')
cat("  ﻿   model1b <- glmer(y ~ severe +  Rx + time + Rx*time + (1 | id), data=depress, family=binomial, control = glmerControl(optimizer ='Nelder_Mead') )", '\n')
cat("  ", '\n')
cat("\033[1;33m## ﻿GEE using exchangable ----------- \033[0m ", '\n')
cat("     model.gee <- gee(y ~ severe  + Rx + time + Rx*time, id, data=depress, family=binomial, corstr='exchangeable') ", '\n')
cat("  ﻿   summary(model.gee)", '\n')
cat("  ", '\n')

} }

